// Generated by https://quicktype.io

export interface AllPokemon {
    count:    number;
    next:     string;
    previous: null;
    results:  SmallPokemon[];
}

export interface SmallPokemon {
    name: string;
    url:  string;
}

export interface Pokemon {
    name: string;
    id: string;
    image: string;

}


export {}